wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699408953.345185
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.9.13
      5: 0.16.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: mean_squared_logarithmic_error
metrics:
  desc: null
  value:
  - mean_squared_error
  - mean_absolute_percentage_error
learning_rate:
  desc: null
  value: 0.001
